version: '3.9'

services:

  cinevect:
    container_name: cinevect
    image: cinevect:1.1
    ports:
      - "5000:5000"
    environment:
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_ENVIRONMENT=${PINECONE_ENVIRONMENT}
      - PINECONE_INDEX=${PINECONE_INDEX}
