version: '3.9'

services:

  cinevect:
    container_name: cinevect
    image: cinevect:latest
    ports:
      - "5000:5000"
    environment:
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_ENVIRONMENT=${PINECONE_ENVIRONMENT}
      - PINECONE_INDEX=${PINECONE_INDEX}
      - WEAVIATE_CLIENT_URL=${WEAVIATE_CLIENT_URL}
      - WEAVIATE_API_KEY=${WEAVIATE_API_KEY}
      - QDRANT_URL=${QDRANT_URL}
      - QDRANT_API_KEY=${QDRANT_API_KEY}
      - SENTENCE_TRANSFORMERS_MODEL=./all-mpnet-base-v2
    networks:
      - cinevect-network
    depends_on:
      - weaviate

  cinevect-ui:
    container_name: cinevect-ui
    image: cinevect-ui:latest
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    networks:
      - cinevect-network
    depends_on:
      - cinevect

networks:
  cinevect-network:
